server:
    port: 8080
    context-path: #/liuzh/

spring:
  datasource:
    url: jdbc:mysql://59.110.216.161:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: JDKLSAJF&*&*(#$%#$&$%&<>?<>?HFCHSJHD
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

mybatis:
  type-aliases-package: com.personalblog
  mapper-locations: classpath:mybatis/*.xml #Mapper的xml文件