server:
    port: 8080
    context-path:

spring:
  datasource:
    url: jdbc:mysql://47.95.148.210:3306/${pole-config.dbName}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: Root-123
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

mybatis:
  type-aliases-package: com.personalblog
  mapper-locations: classpath:mybatis/*.xml #Mapper的xml文件

pole-config:
  logPath: /Users/eric/logs/localhost_access_log.2018-03-27.txt
  dbName: data_statistics
